server:
  port: 8050
spring:
  application:
    name: aureport-ultra
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev,local

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
