spring:
  datasource:
    username: urp
    password: T7nZ7weNG4FBFi75
    url: jdbc:mysql://192.168.101.188:3306/urp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

aureport-ultra:
  servletPrefix: report
  fileStoreDir: /home/coding/aureport-ultra/reports
  debug: true
