server:
  port: 8050
spring:
  application:
    name: aureport-ultra  # 应用名

  profiles:
    active: dev,local

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
