/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoHeight: typeof import('./../components/tree/auto-height.vue')['default']
    Button: typeof import('./../components/button/index.vue')['default']
    ButtonGroup: typeof import('./../components/button-group/index.vue')['default']
    Checkbox: typeof import('./../components/checkbox/index.vue')['default']
    CheckboxGroup: typeof import('./../components/checkbox-group/index.vue')['default']
    Col: typeof import('./../components/col/index.vue')['default']
    ColorPicker: typeof import('./../components/color-picker/index.vue')['default']
    DatePicker: typeof import('./../components/date-picker/index.vue')['default']
    Dialog: typeof import('./../components/dialog/index.vue')['default']
    Divider: typeof import('./../components/divider/index.vue')['default']
    Form: typeof import('./../components/form/index.vue')['default']
    FormItem: typeof import('./../components/form-item/index.vue')['default']
    Input: typeof import('./../components/input/index.vue')['default']
    InputNumber: typeof import('./../components/input-number/index.vue')['default']
    Loading: typeof import('./../components/loading/index.vue')['default']
    Message: typeof import('./../components/message/index.vue')['default']
    Messagebox: typeof import('./../components/messagebox/index.vue')['default']
    Option: typeof import('./../components/option/index.vue')['default']
    Pane: typeof import('./../components/tabs/pane.vue')['default']
    Radio: typeof import('./../components/radio/index.vue')['default']
    RadioGroup: typeof import('./../components/radio-group/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./../components/row/index.vue')['default']
    Select: typeof import('./../components/select/index.vue')['default']
    Switch: typeof import('./../components/switch/index.vue')['default']
    Tabs: typeof import('./../components/tabs/index.vue')['default']
    Tag: typeof import('./../components/tag/index.vue')['default']
    Tree: typeof import('./../components/tree/index.vue')['default']
    TreeNode: typeof import('./../components/tree/tree-node.vue')['default']
  }
}
